# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/playing_cards',
                'doc_host': 'https://PedroHussain.github.io',
                'git_url': 'https://github.com/PedroHussain/playing_cards',
                'lib_path': 'playing_cards'},
  'syms': {'playing_cards.core': {'playing_cards.core.foo': ('core.html#foo', 'playing_cards/core.py')}}}